[package]
name = "workflow-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
workflow-core-macros = { path = "macros/" }

[target.'cfg(not(target_arch = "bpf"))'.dependencies]
async-std = { version = "1.12.0", features = ['attributes'] }
futures = "0.3.21"
