[package]
name = "workflow-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
workflow-core-macros = { path = "macros/" }
cfg-if = "1.0.0"

[target.'cfg(not(target_arch = "bpf"))'.dependencies]
async-std = { version = "1.12.0", features = ['attributes'] }
futures = "0.3.21"
manual_future = "0.1.1"
thiserror = "1.0.0"
triggered = "0.1.2"

[target.'cfg(not(any(target_arch = "bpf", target_arch = "wasm32")))'.dependencies]
tokio = { version = "1.20.1", default-features = false, features = ['io-util','time','sync','macros','rt'] }
